"""Coach: explainable-AI rules companion.

When a noteworthy event happens (penalty, foul, card, corner, goal), "Coach"
explains the rule in one friendly sentence for casual fans — generated by
Granite, grounded on the Laws of the Game parsed by IBM Docling
(data/rules/laws_of_the_game.md). Vetted canonical sentences are the trusted
fallback, so Coach is always correct even without an LLM (e.g. on the cloud).
"""

from __future__ import annotations

from pathlib import Path

RULES_DIR = Path(__file__).resolve().parent.parent / "data" / "rules"

# Vetted, source-cited explanations (the trusted fallback + eval target).
CANONICAL = {
    "penalty": "Penalty: a defender committed a foul or deliberate handball inside "
               "their own box, so the attacking team gets one shot from twelve yards "
               "with only the goalkeeper to beat.",
    "foul": "Foul: a player challenged carelessly, recklessly or with too much force "
            "(a trip, push, hold or handball), so the other team restarts with a free kick.",
    "card": "Card: yellow is a formal warning for offences like a reckless foul, dissent "
            "or time-wasting, while red sends the player off for a serious offence and "
            "forces their team to play a player short.",
    "corner": "Corner: the ball crossed the goal line off a defender without going in, so "
              "the attacking team restarts from the corner arc and tries to deliver it into the box.",
    "goal": "Goal: the whole ball crossed the line between the posts and under the bar, and "
            "it stands as long as there was no offside, handball or other offence in the build-up.",
}
LAW_REF = {"penalty": "Law 14", "foul": "Law 12", "card": "Law 12",
           "corner": "Law 17", "goal": "Law 10"}


def classify(event_type: str, subtype: str) -> str | None:
    """Map a Metrica event (type, subtype) to a Coach category, or None."""
    t = (event_type or "").upper()
    s = (subtype or "").upper()
    if "PENALTY" in s:
        return "penalty"
    if t == "CARD":
        return "card"
    if t.startswith("FAULT"):
        return "foul"
    if t == "SET PIECE" and "CORNER" in s:
        return "corner"
    if t == "SHOT" and "GOAL" in s:
        return "goal"
    return None


def load_coach_events(game: int, t0: float, dur: float):
    """Return [(t, category)] of Coach-worthy events in the window, deduped."""
    import pandas as pd
    from core.metrica import DATA_DIR
    df = pd.read_csv(DATA_DIR / f"g{game}_RawEventsData.csv")
    out = []
    last_t = -99.0
    for _, r in df.iterrows():
        t = r.get("Start Time [s]")
        if t != t or t < t0 or t > t0 + dur:
            continue
        cat = classify(str(r.get("Type", "")), str(r.get("Subtype", "")))
        if cat and float(t) - last_t > 2.0:
            out.append([round(float(t), 1), cat])
            last_t = float(t)
    return out


def _load_rule_sections() -> dict[str, str]:
    """Parse the Laws KB (Docling when available, else markdown) into
    {category: law text} for grounding Granite."""
    path = RULES_DIR / "laws_of_the_game.md"
    text = None
    try:
        from docling.document_converter import DocumentConverter
        text = DocumentConverter().convert(str(path)).document.export_to_markdown()
    except Exception:
        try:
            text = path.read_text(encoding="utf-8")
        except Exception:
            return {}
    sections = {}
    current = None
    buf: list[str] = []
    for line in text.splitlines():
        if line.startswith("## "):
            if current:
                sections[current] = " ".join(buf).strip()
            head = line[3:].lower()
            current = next((c for c in CANONICAL if c in head), None)
            buf = []
        elif current:
            buf.append(line.strip())
    if current:
        sections[current] = " ".join(buf).strip()
    return sections


_SECTIONS: dict[str, str] | None = None


def explain(category: str, provider=None) -> str:
    """One-sentence Coach explanation. Granite-generated and Docling-grounded
    when a warm provider is given; otherwise the vetted canonical sentence."""
    if category not in CANONICAL:
        return ""
    if provider is not None and getattr(provider, "is_warm", lambda: False)():
        global _SECTIONS
        if _SECTIONS is None:
            _SECTIONS = _load_rule_sections()
        law = _SECTIONS.get(category, "")
        prompt = (
            "You are 'Coach', a warm football pundit explaining the game to a "
            "first-time viewer. In ONE friendly sentence, explain what a "
            f"{category} is, grounded in this rule:\n{law}\n"
            "Keep it plain and concrete. No preamble."
        )
        try:
            out = provider.generate(prompt, max_tokens=70)
        except Exception as exc:
            # Degrade to the vetted canonical sentence, but log so a real
            # signature/programming error doesn't silently serve fallback forever.
            import sys
            print(f"Coach: Granite call failed ({exc!r}); using canonical fallback",
                  file=sys.stderr)
            out = None
        if out and len(out.strip()) > 20:
            return out.strip()
    return CANONICAL[category]
